use-sort:
    group:
        - _main
        - Mmoreram
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
  /*
   * This file is part of PhuninNode.
   *
   ** (c) 2013 - 2015 Cees-Jan Kiewiet
   *
   * For the full copyright and license information, please view the LICENSE
   * file that was distributed with this source code.
   */
