language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
branches:
  only:
    - master
before_script:
  - mkdir -p build/cov
  - composer self-update
  - composer install
script: phpunit
after_script:
  - php vendor/bin/coveralls -v
notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true