language: php
php:
  - 5.4
  - 5.5
branches:
  only:
    - master
before_script:
  - mkdir -p build/cov
  - composer self-update
  - composer install
script: phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true
after_script: php vendor/bin/coveralls