language: php
php:
  - 5.4
  - 5.5
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
branches:
  only:
    - master
before_script:
  - composer install
script: php vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true
after_script: php vendor/bin/coveralls